from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request body for the main chat endpoint."""

    conversation_id: str = Field(..., min_length=1)
    message: str = Field(..., min_length=1)
    system_prompt: Optional[str] = None
    use_tools: bool = False


class ChatResponse(BaseModel):
    """Response returned by the main chat endpoint."""

    conversation_id: str
    message: str
    tool_calls: list[dict[str, Any]] = Field(default_factory=list)
    timestamp: datetime
    model: str


class AgentPlan(BaseModel):
    """Structured plan generated by the planning agent."""

    steps: list[str] = Field(default_factory=list)
    reasoning: str = ""
    tools_needed: list[str] = Field(default_factory=list)
